# Generated by Django 3.2.5 on 2021-07-14 20:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Person',
            fields=[
                ('first_name', models.CharField(max_length=10)),
                ('last_name', models.CharField(max_length=10)),
                ('id', models.CharField(max_length=8, primary_key=True, serialize=False)),
                ('phone_number', models.CharField(max_length=10)),
                ('eamil', models.EmailField(max_length=20)),
                ('username', models.CharField(max_length=8)),
                ('password', models.CharField(max_length=12)),
            ],
        ),
    ]
